### ISSUE TITLE
desktop?

### ISSUE THREAD

**Issue by Fishparcle** [Rachmanin0xFF/jwst-twitter-bot#4]
JWST Photo Bot subscriber right from the first post, It was really nice to see pictures from backstage and it's unfair that this ended like this.
Maybe you can work on adapting script for desktop manual use with a simple config file (for size, time, etc) to download pictures? This would be so great

**Comment by Rachmanin0xFF** [comment]
Glad to hear you liked it; I added instructions for desktop use and put a few more options in the config.ini file.

**Comment by Fishparcle** [comment]
thanks a lot, have a great time and luck
